# Generated by Django 5.2 on 2025-04-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='WasteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('compost', 'Compost (Decomposed organic matter)'), ('vermicompost', 'Vermicompost (Earthworm processed compost)'), ('cow_dung', 'Cow Dung Manure (Natural fertilizer)'), ('poultry_manure', 'Poultry Manure (Rich in nitrogen)'), ('green_manure', 'Green Manure (Fresh plant material)'), ('bio_fertilizer', 'Bio-Fertilizer (Microbial based)'), ('organic_manure', 'Organic Manure (Mixed organic materials)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
