# Generated by Django 5.2 on 2025-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_organicmanure_organicproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicmanure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organic_manures/'),
        ),
        migrations.AddField(
            model_name='organicproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organic_products/'),
        ),
    ]
