# Generated by Django 5.2 on 2025-04-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_organicmanure_image_organicproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organicmanure',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organicproduct',
            name='image',
        ),
    ]
