# Generated by Django 5.2 on 2025-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_wasteseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteSeller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='password',
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
