# Generated by Django 5.2 on 2025-04-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_delete_wasteseller_remove_seller_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
